### ISSUE TITLE
Scrolling through model

### ISSUE THREAD

**Issue by Jasper8888** [MicrosoftDocs/powerbi-docs.es-es#19]
Hi, 
It would be usefull if one can scroll through a model by left-click on the canvas and hold the button. Mouse movement will now navigate through the model. 

---
#### Documentdetails

⚠ *Dit gedeelte niet bewerken. Het is vereist om problemen te koppelen tussen docs.microsoft.com en GitHub.*

* ID: f4cfe8c6-b047-1277-8726-0d45d3630b8d
* Version Independent ID: b2e24404-209e-f043-b749-2e2e865a9e79
* Content: [Modelweergave in Power BI Desktop gebruiken (preview) - Power BI](https://docs.microsoft.com/nl-nl/power-bi/desktop-modeling-view)
* Content Source: [powerbi-docs/desktop-modeling-view.md](https://github.com/MicrosoftDocs/powerbi-docs.nl-nl/blob/live/powerbi-docs/desktop-modeling-view.md)
* Service: **powerbi**
* GitHub Login: @davidiseminger
* Microsoft Alias: **davidi**

**Comment by CeciAc** [comment]
Issue moved to [MicrosoftDocs/powerbi-docs #795](https://github.com/MicrosoftDocs/powerbi-docs/issues/795) via [**ZenHub**](https://www.zenhub.com/)

**Comment by CeciAc** [comment]
Hello, @Jasper8888 

Your contribution is much appreciated. Your feedback is related to the original documentation.
Hence, we are migrating this issue to the English repo. Please review the status of the issue here - https://github.com/MicrosoftDocs/powerbi-docs/issues/795.

We truly appreciate your contribution to our articles. 

Kind regards,
Microsoft DOCS International Team
