### ISSUE TITLE
missing field

### ISSUE THREAD

**Issue by LidiaVonk** [MicrosoftDocs/powerbi-docs.es-es#21]
Field Senior in the calculation for "new rank" isn't available in the datasource http://www.bankrate.com/finance/retirement/best-places-retire-how-state-ranks.aspx . 

---
#### Documentdetails

⚠ *Dit gedeelte niet bewerken. Het is vereist om problemen te koppelen tussen docs.microsoft.com en GitHub.*

* ID: f510cb29-4222-72f8-ff8e-58553c856234
* Version Independent ID: cbde387d-8cbc-50ed-5665-54985b9ebcc1
* Content: [Gegevens van meerdere gegevensbronnen vormgeven en combineren - Power BI](https://docs.microsoft.com/nl-nl/power-bi/desktop-shape-and-combine-data#feedback)
* Content Source: [powerbi-docs/desktop-shape-and-combine-data.md](https://github.com/MicrosoftDocs/powerbi-docs.nl-nl/blob/live/powerbi-docs/desktop-shape-and-combine-data.md)
* Service: **powerbi**
* GitHub Login: @davidiseminger
* Microsoft Alias: **davidi**

**Comment by CeciAc** [comment]
Issue moved to [MicrosoftDocs/powerbi-docs #936](https://github.com/MicrosoftDocs/powerbi-docs/issues/936) via [**ZenHub**](https://www.zenhub.com/)

**Comment by CeciAc** [comment]
Hello, @LidiaVonk 

Your contribution is much appreciated. Your feedback is related to the original documentation.
Hence, we are migrating this issue to the English repo. Please review the status of the issue here - https://github.com/MicrosoftDocs/powerbi-docs/issues/936

We truly appreciate your contribution to our articles. 

Kind regards,
Microsoft DOCS International Team
