### ISSUE TITLE
Problema No se ha configurado la referencia del objeto

### ISSUE THREAD

**Issue by akelazr** [MicrosoftDocs/powerbi-docs.es-es#26]
In this page is indicate as solution to the problem "No se ha configurado referencia del objeto" when connect to an Oracle DB . Copy oraons.dll but don´t specify the destination. Where should i copy this file?

---
#### Detalles del documento

⚠ *No edite esta sección. Se requiere para docs.microsoft.com ➟ Vinculación de problema de GitHub.*

* ID: 382f269e-2072-ec03-7c88-335cbd5df919
* Version Independent ID: 46a896f9-4707-adc3-72cd-5444a5d0f802
* Content: [Conectarse a una base de datos de Oracle - Power BI](https://docs.microsoft.com/es-es/power-bi/desktop-connect-oracle-database#feedback)
* Content Source: [powerbi-docs/desktop-connect-oracle-database.md](https://github.com/MicrosoftDocs/powerbi-docs.es-es/blob/live/powerbi-docs/desktop-connect-oracle-database.md)
* Service: **powerbi**
* Sub-service: **powerbi-desktop**
* GitHub Login: @davidiseminger
* Microsoft Alias: **davidi**

**Comment by srvbpigh** [comment]
Hello, @akelazr
 
Thank you for your feedback.
 
We are actively reviewing your comments and will get back to you soon.


Kind regards,
Microsoft DOCS International Team

**Comment by CeciAc** [comment]
Issue moved to [MicrosoftDocs/powerbi-docs #1615](https://github.com/MicrosoftDocs/powerbi-docs/issues/1615) via [**ZenHub**](https://www.zenhub.com/)

**Comment by CeciAc** [comment]
Hello, @akelazr

Your contribution is much appreciated. Your feedback is related to the original documentation.
Hence, we are migrating this issue to the English repo. Please review the status of the issue here - https://github.com/MicrosoftDocs/powerbi-docs/issues/1615

We truly appreciate your contribution to our articles. 

Kind regards,
Microsoft DOCS International Team
