### ISSUE TITLE
Granting access to reports

### ISSUE THREAD

**Issue by DaveRuijter** [MicrosoftDocs/powerbi-docs.es-es#3]
You suggest granting users access to the report by pinning a visual to a dashboard and sharing that dashboard. Since we now can share reports directly, probably that's a better suggestion.

---
#### Documentdetails

⚠ *Dit gedeelte niet bewerken. Het is vereist om problemen te koppelen tussen docs.microsoft.com en GitHub.*

* ID: 0fc5abbd-e082-d1e1-109d-6f6cec8854a1
* Version Independent ID: f8affce3-98f2-0cc6-b4de-d9af7ced0fbe
* Content: [Insluiten met webonderdeel Rapport in SharePoint Online - Power BI](https://docs.microsoft.com/nl-nl/power-bi/service-embed-report-spo)
* Content Source: [powerbi-docs/service-embed-report-spo.md](https://github.com/MicrosoftDocs/powerbi-docs.nl-nl/blob/live/powerbi-docs/service-embed-report-spo.md)
* Service: **powerbi**
* GitHub Login: @markingmyname
* Microsoft Alias: **maghan**

**Comment by markingmyname** [comment]
Thank you for your feedback! We will investigate and review if we need to change/add the information suggested.

**Comment by markingmyname** [comment]
Thank you for your feedback! We will investigate and review if we need to change/add the information suggested

**Comment by LisandroSu** [comment]
Issue moved to [MicrosoftDocs/powerbi-docs #156](https://github.com/MicrosoftDocs/powerbi-docs/issues/156) via [**ZenHub**](https://www.zenhub.com/)

**Comment by LisandroSu** [comment]
Hello, @DaveRuijter  
 
Your contribution is much appreciated. Your feedback is related to the original documentation. 
Hence, we are migrating this issue to the English repo. Please review the status of the issue here - https://github.com/MicrosoftDocs/powerbi-docs/issues/156. 
 
We truly appreciate your contribution to our articles.  
 
Kind regards, 
Microsoft DOCS International Team
