### ISSUE TITLE
Update list

### ISSUE THREAD

**Issue by DaveRuijter** [MicrosoftDocs/powerbi-docs.es-es#6]
Please keep the list of audited actions up-to-date.

---
#### Documentdetails

⚠ *Dit gedeelte niet bewerken. Het is vereist om problemen te koppelen tussen docs.microsoft.com en GitHub.*

* ID: a0e8bce0-95c1-07f7-d3a3-a1c22bd21f29
* Version Independent ID: dddd1e30-4a88-1293-1264-3214cc4b6dc8
* Content: [Auditing gebruiken binnen uw organisatie - Power BI](https://docs.microsoft.com/nl-nl/power-bi/service-admin-auditing)
* Content Source: [powerbi-docs/service-admin-auditing.md](https://github.com/MicrosoftDocs/powerbi-docs.nl-nl/blob/live/powerbi-docs/service-admin-auditing.md)
* Service: **powerbi**
* GitHub Login: @mgblythe
* Microsoft Alias: **mblythe**

**Comment by LisandroSu** [comment]
Hello, @DaveRuijter , 
  
Thank you for your feedback. 
  
We are actively reviewing your comments and will get back to you soon. 
 
Kind regards, 
Microsoft DOCS International Team

**Comment by CeciAc** [comment]
Hello, @DaveRuijter

Your contribution is much appreciated. Your feedback is related to the original documentation.
Hence, we are migrating this issue to the English repo. Please review the status of the issue here - XXX.

We truly appreciate your contribution to our articles. 

Kind regards,
Microsoft DOCS International Team
